language: python
python:
  - "3.9"
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest
#Adding a line to trigger new commit
#Travis only runs builds on the commits you push after you’ve added a .travis.yml file.
